version: '3.8'

volumes:
  db-data:

services:
  # php
  app:
    build: ./docker/php
    volumes:
      - $BACKEND_DIR:/laravel

  # nginx
  web:
    build: ./docker/nginx
    ports:
      - $NGINX_PORT:80
    volumes:
      - $BACKEND_DIR:/laravel
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    working_dir: $NGINX_DIR

  # MySQL
  db:
    build:
      context: ./docker/mysql
      args:
        MYSQL_DATABASE: $MYSQL_DATABASE
        MYSQL_USER: $MYSQL_USER
        MYSQL_PASSWORD: $MYSQL_PASSWORD
        MYSQL_ROOT_PASSWORD: $MYSQL_ROOT_PASSWORD
        TZ: $TZ
    volumes:
      - db-data:/var/lib/mysql
    ports:
      - $DB_PORT:3306

  # ngrok
  ngrok:
    image: wernight/ngrok
    ports:
      - 4040:4040
    environment:
      NGROK_AUTH: ${NGROK_AUTH}
      NGROK_PROTOCOL: http
      NGROK_PORT: web:80
